import React from 'react';
import figma from '@figma/code-connect';
import { AppBar } from '../src/core/AppBar/AppBar';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    AppBar,
    'https://www.figma.com/design/ZwJ3feoFnLiV3JNYqI7A3c/-Limited-Support--Brightlayer-UI-Component-Sticker-Sheet?node-id=4417-16',
    {
        props: {
            leftIcon: figma.instance('Left Icon'),
            showLeftIcon: figma.boolean('Show Left Icon'),
            showIconButtonRow: figma.boolean('Show Icon Button Row'),
        },
        example: (props) => <AppBar {...props} />,
    }
);
