import React from 'react';
import { ChannelValue } from '../src/core/ChannelValue/ChannelValue';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    ChannelValue,
    'https://www.figma.com/design/ZwJ3feoFnLiV3JNYqI7A3c/-Limited-Support--Brightlayer-UI-Component-Sticker-Sheet?node-id=4055-9521&t=72gEx1GB5cz8M8cN-0',
    {
        props: {
            value: figma.string('Value'),
            units: figma.string('Units'),
            icon: figma.instance('Icon'),
            showUnits: figma.boolean('Show Units'),
        },
        example: (props) => <ChannelValue {...props} />,
    }
);
