import React from 'react';
import { DrawerLite } from '../src/core/DrawerLite/DrawerLite';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    DrawerLite,
    'https://www.figma.com/design/ZwJ3feoFnLiV3JNYqI7A3c/-Limited-Support--Brightlayer-UI-Component-Sticker-Sheet?node-id=10417-143805&m=dev',
    {
        props: {
            activeItem: 'string',
            children: 'string',
        },
        example: (props) => <DrawerLite activeItem={props.activeItem}>{props.children}</DrawerLite>,
    }
);
