import React from 'react';
import { DrawerNavItem } from '../src/core/Drawer/DrawerNavItem';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    DrawerNavItem,
    'https://www.figma.com/design/ZwJ3feoFnLiV3JNYqI7A3c/-Limited-Support--Brightlayer-UI-Component-Sticker-Sheet?node-id=4861-60988&m=dev',
    {
        props: {
            icon: figma.instance('Icon'),
            title: figma.string('Title'),
        },
        example: (props) => <DrawerNavItem {...props} />,
    }
);
