import React from 'react';
import { EmptyState } from '../src/core/EmptyState/EmptyState';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    EmptyState,
    'https://www.figma.com/design/ZwJ3feoFnLiV3JNYqI7A3c/-Limited-Support--Brightlayer-UI-Component-Sticker-Sheet?node-id=4376-82&m=dev',
    {
        props: {
            icon: figma.instance('Icon'),
            showButton: figma.boolean('Show Button'),
            description: figma.string('Description'),
            showDescription: figma.boolean('Show Description'),
            title: figma.string('Title'),
        },
        example: (props) => <EmptyState {...props} />,
    }
);
