import React from 'react';
import { FileDragUpload } from '../src/core/FileDragUpload/FileDragUpload';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    FileDragUpload,
    'https://www.figma.com/design/ZwJ3feoFnLiV3JNYqI7A3c/-Limited-Support--Brightlayer-UI-Component-Sticker-Sheet?node-id=30734-22004&m=dev',
    {
        props: {
            title: figma.string('Title'),
            instruction: figma.string('Instruction'),
            info: figma.string('Info'),
            icon: figma.instance('Icon'),
        },
        example: (props) => <FileDragUpload {...props} />,
    }
);
