import React from 'react';
import { ListItemTag } from '../src/core/ListItemTag/ListItemTag';
import figma from '@figma/code-connect';

/**
 * -- This file was auto-generated by Code Connect --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
    ListItemTag,
    'https://www.figma.com/design/ZwJ3feoFnLiV3JNYqI7A3c/-Limited-Support--Brightlayer-UI-Component-Sticker-Sheet?node-id=4364-2123&m=dev',
    {
        props: {},
        example: () => <ListItemTag label={'Label'} />,
    }
);
