name: Build

on:
    push:
        branches: ['dev', 'master']
    pull_request:
        branches: ['dev', 'master']
    pull_request_target:
        types:
            - opened
        branches:
            - '*/*'

permissions:
    pull-requests: write
    contents: read

jobs:
    prettier_lint:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn --immutable
            - run: yarn prettier
            - run: yarn lint

    unit_test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn --immutable
            - run: yarn test --coverage
            - name: Upload to Codecov
              uses: codecov/codecov-action@v5
              with:
                  directory: ./coverage/
                  files: clover.xml
                  flags: unittests
                  name: codecov-report
                  verbose: true

    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [16.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'
            - run: yarn --frozen-lockfile
            - run: yarn build
            - name: Save build
              uses: actions/upload-artifact@v4
              with:
                  name: build
                  if-no-files-found: error
                  path: build

    cypress-run:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [16.x]
        needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'yarn'

            - name: Cypress install
              uses: cypress-io/github-action@v6
              with:
                  runTests: false

            - name: Download the build folder
              uses: actions/download-artifact@v4
              with:
                  name: build
                  path: build

            - name: Cypress run
              uses: cypress-io/github-action@v6
              with:
                  start: yarn start:cytest && yarn cy:run
                  wait-on: ${{ matrix.node-version == 16 && 'http://[::1]:3000' || 'http://localhost:3000' }}
                  wait-on-timeout: 300
                  browser: chrome

            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v5
              with:
                  directory: cypress-coverage
                  files: clover.xml
                  flags: uitests
                  name: codecov-report
                  verbose: true
