
name: CI-BlackDuck-SCA-Basic

on:
  push:
    branches: [main, master, dev, feature/*]
  pull_request:
    branches: [main, master, dev]
  workflow_dispatch:

jobs:
  blackduck-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - react/apps/design-patterns
          #- react/apps/demo
          #- react/apps/showcase
          #- react/apps/storybook
          #- react/apps/themeShowcase
          #- react/apps/workflow/example-vite
          #- react/apps/workflow/example
          #- react/packages/cli-templates
          #- react/packages/component-library
          #- react/packages/login-workflow
          #- react/packages/themes

    defaults:
      run:
        working-directory: ${{ matrix.app }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Read Version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Black Duck Scan
        uses: blackduck-inc/black-duck-security-scan@v2.3.0
        env:
          DETECT_PROJECT_NAME: ${{ vars.PROJECT_NAME }}
          DETECT_PROJECT_VERSION_NAME: ${{ env.VERSION }}
        with:
          blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
          blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}