
name: CI-BlackDuck-SCA-Basic

on:
  push:
    branches: [main, master, dev,feature/*]
  pull_request:
    branches: [main, master, dev]
  workflow_dispatch:

jobs:
  blackduck-scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - apps/demo

    defaults:
      run:
        working-directory: ${{ matrix.app }}

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Read Version from package.json
        id: get_version
        run: |
          VERSION=$(jq -r .version package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV